//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalek {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dalek.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credentials.json.
        /// </summary>
        internal static string PathJsonCredentials {
            get {
                return ResourceManager.GetString("PathJsonCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.json.
        /// </summary>
        internal static string PathOAuthSessionToken {
            get {
                return ResourceManager.GetString("PathOAuthSessionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential file saved to: {strings.PathOAuthSessionToken}.
        /// </summary>
        internal static string Program_Main_Credential_Saved_To_PathOAuthSessionToken {
            get {
                return ResourceManager.GetString("Program_Main_Credential_Saved_To_PathOAuthSessionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalek speaks.
        /// </summary>
        internal static string Program_Main_Dalek_speaks {
            get {
                return ResourceManager.GetString("Program_Main_Dalek_speaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found..
        /// </summary>
        internal static string Program_Main_No_data_found_ {
            get {
                return ResourceManager.GetString("Program_Main_No_data_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is obvious..
        /// </summary>
        internal static string Program_Main_This_is_obvious_ {
            get {
                return ResourceManager.GetString("Program_Main_This_is_obvious_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will explain later.
        /// </summary>
        internal static string Program_Main_We_will_explain_later {
            get {
                return ResourceManager.GetString("Program_Main_We_will_explain_later", resourceCulture);
            }
        }
    }
}
